union XMLRPCLegalValue {
    1:i32 int_value,
    2:string string_value,
}
service MasterAPI {
    list<string> deleteParam(1:string key, 2:string caller_id),
    list<string> getParam(1:string key, 2:string caller_id),
    list<string> getParamNames(1:string caller_id),
    list<string> getPid(1:string caller_id),
    list<string> getPublishedTopics(1:string subgraph, 2:string caller_id),
    list<string> getSystemState(1:string caller_id),
    list<string> getTopicTypes(1:string caller_id),
    void getUri(),
    list<string> hasParam(1:string key, 2:string caller_id),
    list<string> lookupNode(1:string node, 2:string caller_id),
    list<string> lookupService(1:string service_, 2:string caller_id),
    void param_update_task(1:string caller_api, 2:string param_value, 3:string param_key, 4:string caller_id),
    list<string> registerPublisher(1:string topic, 2:string topic_type, 3:string caller_api, 4:string caller_id),
    list<string> registerService(1:string caller_api, 2:string service_, 3:string caller_id, 4:string service_api),
    list<string> registerSubscriber(1:string topic_type, 2:string caller_api, 3:string caller_id),
    list<string> searchParam(1:string key, 2:string caller_id),
    list<string> setParam(1:XMLRPCLegalValue value, 2:string key, 3:string caller_id),
    list<string> shutdown(1:string msg, 2:string caller_id),
    list<string> subscribeParam(1:string caller_api, 2:string key, 3:string caller_id),
    list<string> unregisterPublisher(1:string topic, 2:string caller_api, 3:string caller_id),
    list<string> unregisterService(1:string service_, 2:string caller_id, 3:string service_api),
    list<string> unregisterSubscriber(1:string topic, 2:string caller_api, 3:string caller_id),
    list<string> unsubscribeParam(1:string caller_api, 2:string key, 3:string caller_id),
}
